#!/usr/bin/env bash
# Install script to install citadel on your system


set -eux

sudo mkdir -p /etc/citadel
sudo chmod -v 755 /etc/citadel

# Log dir
sudo mkdir -pv /var/log/citadel
sudo chown -v root:root /var/log/citadel
sudo chmod -v 777 /var/log/citadel
 
# Images
sudo mkdir -pv /etc/citadel/images
sudo chmod -v 755 /etc/citadel/images
sudo cp -vr images/* /etc/citadel/images
sudo chown -Rv root:root /etc/citadel/images/*
sudo chmod -Rv 644 /etc/citadel/images/definitions/*
sudo chmod -Rv 644 /etc/citadel/images/files/*
sudo chmod -v 755 /etc/citadel/images/definitions
sudo chmod -v 755 /etc/citadel/images/files
 
# Profiles
sudo mkdir -pv /etc/citadel/profiles
sudo chmod -v 755 /etc/citadel/profiles
sudo cp -v profiles/* /etc/citadel/profiles
sudo chown -v root:root /etc/citadel/profiles/*
sudo chmod -v 644 /etc/citadel/profiles/*
 
# Autostart
sudo mkdir -pv $HOME/.config/autostart
sudo cp -v etc/autostart/* $HOME/.config/autostart
 
# Python lib
sudo cp -vr libcitadel/citadel /usr/lib64/python3.13/site-packages

# Bins
sudo cp -v etc/bin/build-images /sbin/build-images
sudo chown -v root:root /sbin/build-images
sudo chmod -v 755 /sbin/build-images
 
sudo cp -v etc/bin/cookiepatch /sbin/cookiepatch
sudo chown -v root:root /sbin/cookiepatch
sudo chmod -v 755 /sbin/cookiepatch
 
sudo cp etc/bin/import-profiles /sbin/import-profiles
sudo chown root:root /sbin/import-profiles
sudo chmod 755 /sbin/import-profiles
 
sudo cp -v etc/bin/run-container /sbin/run-container
sudo chown -v root:root /sbin/run-container
sudo chmod -v 755 /sbin/run-container
 
sudo cp -v etc/bin/sync-desktop /sbin/sync-desktop
sudo chown -v root:root /sbin/sync-desktop
sudo chmod -v 755 /sbin/sync-desktop
 
sudo cp -v etc/bin/upgrade-containers /sbin/upgrade-containers
sudo chown -v root:root /sbin/upgrade-containers
sudo chmod -v 755 /sbin/upgrade-containers
 
sudo cp -v etc/bin/create-container /sbin/create-container
sudo chown -v root:root /sbin/create-container
sudo chmod -v 755 /sbin/create-container
 
sudo cp -v etc/bin/upgrade-system /sbin/upgrade-system
sudo chown -v root:root /sbin/upgrade-system
sudo chmod -v 755 /sbin/upgrade-system

# Systemd
sudo cp -v etc/systemd/services/sync-desktop.service /etc/systemd/system/sync-desktop.service
sudo chown -v root:root /etc/systemd/system/sync-desktop.service
sudo chmod -v 644 /etc/systemd/system/sync-desktop.service
 
sudo cp -v etc/systemd/services/upgrade-containers.service /etc/systemd/system/upgrade-containers.service
sudo chown -v root:root /etc/systemd/system/upgrade-containers.service
sudo chmod -v 644 /etc/systemd/system/upgrade-containers.service
 
sudo cp -v etc/systemd/services/upgrade-system.service /etc/systemd/system/upgrade-system.service
sudo chown -v root:root /etc/systemd/system/upgrade-system.service
sudo chmod -v 644 /etc/systemd/system/upgrade-system.service

sudo cp -v etc/systemd/timers/sync-desktop.timer /etc/systemd/system/sync-desktop.timer
sudo chown -v root:root /etc/systemd/system/sync-desktop.timer
sudo chmod -v 644 /etc/systemd/system/sync-desktop.timer
 
sudo cp -v etc/systemd/timers/upgrade-containers.timer /etc/systemd/system/upgrade-containers.timer
sudo chown -v root:root /etc/systemd/system/upgrade-containers.timer
sudo chmod -v 644 /etc/systemd/system/upgrade-containers.timer
 
sudo cp -v etc/systemd/timers/upgrade-system.timer /etc/systemd/system/upgrade-system.timer
sudo chown -v root:root /etc/systemd/system/upgrade-system.timer
sudo chmod -v 644 /etc/systemd/system/upgrade-system.timer

sudo systemctl enable --now upgrade-containers.timer
sudo systemctl enable --now upgrade-system.timer
sudo systemctl enable --now sync-desktop.timer

# Sudo
sudo mkdir -pv /etc/sudoers.d
sudo chown -v root:root /etc/sudoers.d
sudo chmod -v 700 /etc/sudoers.d 

sudo cp -v etc/citadel /etc/sudoers.d/citadel
sudo chown -v root:root /etc/sudoers.d/citadel
sudo chmod -v 600 /etc/sudoers.d/citadel

# Autostart entries
mkdir -pv ~/.config/autostart
cp -v etc/autostart/* ~/.config/autostart

import-profiles
sudo build-images

echo "Done. Please make sure to initialize a incus storage pool with name citadel."